Вестка главной страницы
htmlacademy-adaptive/1815305-sedona-23 pull request #3
Opened 2021-07-27 18:46 UTC by Dav91

2021-07-31 21:26 UTC, vladpovelitsa requested changes
Привет, проверил твое задание, еще есть над чем поработать, но в целом всё очень хорошо! Продолжай в том же духе. Там есть несколько небольших правок и нужно будет доверстать блоки, которых пока не хватает. Если ты не знаешь или не успеваешь свертать блок, то лучше не отправляй д/з, а уточни у меня, чтобы я не тратил время на незавершенное задание

2021-07-31 21:26 UTC, vladpovelitsa commented on source/catalog.html
> +        </button>
Поправь здесь форматирование слетело. Дальше по файлам тоже проверь, чтобы я не повторял одно и то же

2021-07-31 21:26 UTC, vladpovelitsa commented on source/catalog.html
> +                        <a href="#">Html Academy</a>
для тегов  <a> проставь на всех страницах ссылки на другие страницы

2021-07-31 21:26 UTC, vladpovelitsa commented on source/catalog.html
> +            <p class="page-main__header--text text">Не можете решится на путешествие из-за курса? Фотографии помогут вам забыть о политике и экономике.</p>
Уточни пожалуйста, для что ты отделяешь при помощи двойного тире -- ?
Класс text не вписывается в методологию БЭМ 
Вот ссылка, прочитай еще раз про неё, если останутся вопросы - задавай
https://ru.bem.info/methodology/quick-start/#%D0%9C%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80

2021-07-31 21:26 UTC, vladpovelitsa commented on source/index.html
> +                    <p class="advantages-section__header--number text-width-lines"> &#8470;1</p>
Не совсем понимаю для чего нужен класс text-width-lines и почему ты используешь html символ вместо обычно №

2021-07-31 21:26 UTC, vladpovelitsa commented on source/index.html
> +                </ul>
здесь ul тебе не нужен, а li замени на div

2021-07-31 21:26 UTC, vladpovelitsa commented on source/index.html
> +            <a class="social-link" href="https://www.youtube.com/">Youtube</a>
как правило, ссылки на внешние ресурсы (другие сайты) делают с атрибутом target="_blank" чтобы браузер открывал ссылку в новой странице. Сделай так же, если в ТЗ не указано обратное

2021-07-31 21:26 UTC, vladpovelitsa commented on source/index.html
> +            <img class="page-copyright__icon" src="img/icon-copyright.svg" width="27" height="34" alt="Картинка копирайта">
как раз знак копирайта можно сделать при помощи  html символа, чтобы не грузить лишнюю картинку пользователю

2021-07-31 21:26 UTC, vladpovelitsa commented on source/catalog.html
> +        </section>
тут нужно сверстать еще целый блок и добавить видео

2021-08-01 10:23 UTC, Dav91 commented on source/index.html
> +                    <p class="advantages-section__header--number text-width-lines"> &#8470;1</p>
text-width-lines использую чтобы задать стили для таких текстов с линиями по бокам

2021-08-01 20:22 UTC, vladpovelitsa requested changes
Есть пара небольших правок, плюс замечание от валидатора
![image](https://user-images.githubusercontent.com/52033843/127784317-eecb9dfc-f035-420c-a124-0d7f2332b121.png)

В остальном всё хорошо, продолжай в том же духе, молодец!

2021-08-01 20:22 UTC, vladpovelitsa commented on source/catalog.html
> +            </ul>
Здесь не нужен ul li  замени ul на обычный div, а li на article - так будет правильнее

2021-08-01 20:22 UTC, vladpovelitsa commented on source/form.html
> +            <img src="img/logotype-mobile.svg.png" alt="Главный логотип">
проверь формат этого изображения

2021-08-01 20:22 UTC, vladpovelitsa commented on source/form.html
> +                </ul>
здесь тоже не нужны ul li и далее в таких же блоках

2021-08-05 16:55 UTC, vladpovelitsa approved these changes

2021-08-05 16:56 UTC, merged